#DOCKER-COMPOSE.YAML

version: '3.8'

services:
  myapp:
    build: .
    restart: always
    volumes:
      - ./src:/app  # src — папка с приложением на хосте (нужно чтобы существовала)
    command: python main.py
